update to reason@3.6.0 & ocaml@4.10.0
esy-ocaml/hello-reason pull request #72
Opened 2020-08-09 22:09 UTC by woeps

I updated `reason` and `ocaml` to current latest version:
- `reason` to `3.6.0`
- `ocaml` to `4.10.0`

Dune lang version was also updated to `1.11` in `dune-project` file.

closes #71

2020-08-09 22:18 UTC, yawaramin approved these changes
Great, thank you.

2020-08-09 22:18 UTC, yawaramin commented on package.json
> +    "ocaml": "~4.10.0",
I think this can be removed? Since `ocaml` is already a runtime dep.

2020-08-09 22:20 UTC, yawaramin commented
@woeps since this PR is upgrading stuff, would you mind upgrading to Esy 0.6.6 for the CI builds: https://github.com/esy-ocaml/hello-reason/blob/903f528740c6689a3213f167f2d22153e8b89cae/.ci/utils/use-esy.yml

2020-08-09 22:23 UTC, Et7f3 requested changes

2020-08-09 22:23 UTC, Et7f3 commented on package.json
>      "@opam/dune": "*",
```suggestion
    "@opam/dune": ">=1.11",
```
because you have updated dune-project.

2020-08-09 22:36 UTC, Et7f3 commented
We still use dune-lang (1.0 or 1.11 with this PR) maybe it is time to use (dune-lang 2.6) so new package that use this template have recent dependencies.

2020-08-09 22:50 UTC, woeps commented
@Et7f3 I updated dune lang to `2.6` in `dune-project`, should I update dune version in `package.json` also to `2.6`?

2020-08-09 22:52 UTC, yawaramin commented on package.json
> +    "@opam/dune": ">=1.11",
Since you set `(lang dune 2.6)`, to avoid any possible issues I would say use version `>= 2.6` here

2020-08-09 22:52 UTC, Et7f3 commented
Yup they must be the same

2020-08-09 23:09 UTC, Et7f3 approved these changes

2020-08-10 07:22 UTC, ulrikstrid commented
Are we using features from fune 2.6 in the dune-project?

2020-08-10 12:04 UTC, woeps commented
> Are we using features from fune 2.6 in the dune-project?

currently `dune-project` just contains:
```
(lang dune 2.6)
```

2020-08-10 15:15 UTC, ulrikstrid approved these changes
I'm fine with merging this, but it might make sense to be more relaxed on the dune version (^2.0.0) since we're not using any of the new/advanced dune features.

2020-08-10 15:22 UTC, yawaramin commented
@ulrikstrid all else being equal, imho I'd prefer this repo to be as up-to-date as possible. Especially because this repo is oriented toward building apps. Library publishers can be taught to relax their dune version requirements.

2020-08-10 15:26 UTC, ulrikstrid commented
What happens when you hit a package with a upper limit on dune @yawaramin?

2020-08-10 15:33 UTC, yawaramin commented
@ulrikstrid send a PR to the package to upgrade dune and in the meanwhile downgrade locally ;-)

Seriously though, I set `>= 2.6.2 < 3.0.0` as my dune version in ReWeb and haven't had any issues with it. From what I can tell none of my dependencies set an upper bound on dune.

2020-08-11 07:03 UTC, ulrikstrid commented
@jordwalke what's your take? I think you hit some dune constraint issue at some point right?

Again, I'm okay with merging this, but what is the "best practice"?

2020-08-14 17:29 UTC, ducaale commented
@woeps if I may ask, how you were able to generate a lockfile that works. This PR worked for me in MacOS but when I tried cloning this repo and manually re-applying your changes in `package.json` and in `dune` but I am getting errors because`refmterr` doesn't support OCaml 4.10.0 yet?

2020-08-14 18:26 UTC, yawaramin commented
@ducaale did you upgrade the `reason` version as well? https://github.com/esy-ocaml/hello-reason/pull/72/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R28

2020-08-14 18:48 UTC, ducaale commented
Yes, I did.

```json
  "dependencies": {
    "@opam/dune": ">=2.6",
    "@reason-native/console": "*",
    "@reason-native/pastel": "*",
    "@esy-ocaml/reason": ">= 3.6.0 < 4.0.0",
    "ocaml": "~4.10.0"
  },
  "devDependencies": {
    "@opam/merlin": "*",
    "@reason-native/rely": "*",
    "refmterr": "*",
    "@opam/odoc": "*"
  }
```

2020-08-17 20:58 UTC, yawaramin commented
@woeps @ulrikstrid can we move this forward? I have no issues with using `(lang dune 2.0)`. Does that unblock this?

2020-08-18 07:39 UTC, jordwalke commented
If this fixes something feel free to merge, and then we can iterate again in more diffs.

But you should probably delete the lockfile and run esy again because I just pushed out a new version of Reason with much wider omp compatibility (you should get reason@3.6.2).

I have historically used this repo to create both apps and libraries. I think we should be encouraging people to upgrade to the latest dependencies as much as possible, however, libraries should have the widest range of compatibility possible. We can make pesy library templates focus on compatibility of dependencies, and it doesn't matter as much for this specific repo (but if I was forced to vote, I'd pick wider compatibility).

Feel free to land. If you update to reason 3.6.2 it will save me a PR. ;)

2020-08-18 11:18 UTC, woeps commented
I will push an update of reason to 3.6.2 tonight (UTC+2).

2020-08-19 05:04 UTC, merged

2020-08-19 05:04 UTC, ulrikstrid commented
Thank you!

2020-08-19 09:34 UTC, Et7f3 commented
dune 2.7 was released just before the merge 😀

2020-08-19 10:54 UTC, woeps commented
@ulrikstrid I just realised my last commit updated dune in esy.lock to 2.7 but I forgot to update that version in other places:

- `package.json` still states `>=2.6`
`- dune-project` still states `2.6`.

Is this an issue I should send another pr for?

2020-08-19 10:57 UTC, ulrikstrid commented
We would rather want to **relax** the dune version to the lowest possible (2.0 probably) since this template can be used for libraries as well and then we don't want to force 2.7 since they will get that anyway.

2020-08-19 21:56 UTC, Et7f3 commented
@woeps it is not an issue esy.lock only contain the last known solution but constraints are good.
@ulrikstrid if project put upper bound it will be <3.0.0 so requiring >=2.6.0 or >=2.7.0 should be fine (although for dune if we add a dune-project file the upper bound shouldn't be needed so it is less than a issue)
I have checked the number of download per month:
1.2.1: 1179
1.11.4: 7286
<2.0 >2.5: ~3k
2.5.1: 19351
2.6.0: 4327
2.6.1: 40041
2.6.2: 35307
2.7.0: 1866 (but released yesterday)
So 2.6 is definitely a good standard and why not 2.7 because it is likely that users will update their lockdir soon (or at least in the month)